#!/bin/sh

DATE=$(date +%Y%m%d-%H-%M-%S)

prefix="/root/mail/new"
numPath="/root/mail"

mkdir -p $prefix
mkdir -p $numPath

if [ ! -f $numPath/emailNumbers ]; then
echo "0" > $numPath/emailNumbers
fi
emailNumbers=`cat $numPath/emailNumbers`
emailNumbers=$(($emailNumbers + 1))
echo $emailNumbers > $numPath/emailNumbers
name="$prefix/letter_$emailNumbers.eml"
echo "$0: $@" >> $name
while IFS= read line
do
echo "$line" >> $name
done

# get to and subject from body
to="$(cat $name | sed -n -e 's/^To: //p' | head -n 1)"
subject="$(cat $name | sed -n -e 's/^Subject: //p' | head -n 1)"

if [-z "$to"]; then
    echo 'no recipient'
    exit 1
fi

echo $to
echo $subject

curl -s --user "$MAILGUN_TOKEN" \
    https://api.mailgun.net/v3/sandbox28d0690f5af045f09f87eff25d2770f6.mailgun.org/messages \
        -F from='ly-root <postmaster@sandbox28d0690f5af045f09f87eff25d2770f6.mailgun.org>' \
        -F to="$to" \
        -F subject="$subject" \
        -F text="$(cat $name)"

# chmod 777 $name
/bin/true
